Repository PAW-KEY/PAWKEY-Android, pull requests merged in 2025-07, with the labels that each got.

#4 [Docs/#3] : 1차과제 README.md 수정
  README.md
Labels: 🐻주완, docs 📝

#10 [Feat/#7] 커스텀 바텀 바
  app/src/main/java/com/paw/key/presentation/ui/community/CommunityScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/community/navigation/CommunityNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/course/CourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/navigation/CourseNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainTab.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/java/com/paw/key/presentation/ui/main/component/MainBottomBar.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/MyPageNavigation.kt
Labels: feature ✨, 🐶민성

#21 [Feat/#18] : home view 생성, component 작업
  app/src/main/java/com/paw/key/core/designsystem/component/PawkeyButton.kt
  app/src/main/java/com/paw/key/core/designsystem/component/SubChip.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/HistoryCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/TopBar.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/TrackingCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/WeatherCard.kt
  app/src/main/res/drawable/ic_home_date_filled.xml
  app/src/main/res/drawable/ic_home_location.xml
  app/src/main/res/drawable/ic_home_location_filled.xml
  app/src/main/res/drawable/ic_home_rainrating.xml
  app/src/main/res/drawable/ic_home_under_arrow.xml
  app/src/main/res/drawable/ic_home_weather.xml
Labels: feature ✨, 🐻주완

#26 [Chore/#25] designsystem color 수정
  app/src/main/java/com/paw/key/core/designsystem/component/PawkeyButton.kt
  app/src/main/java/com/paw/key/core/designsystem/theme/Color.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/HistoryCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/TopBar.kt
Labels: chore 🔮, 🐻주완

#29 [feat/#27] 홈 컴포넌트 수정 및 뷰수정
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/DaytimeCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/HistoryCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/HistoryChip.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/RowCalendar.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/SettingButton.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/TopBar.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/TrackingCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/WeatherCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/res/drawable/ic_home_calendar_dot.xml
  app/src/main/res/drawable/ic_home_setting.xml
  app/src/main/res/drawable/img_home_tracking.png
  app/src/main/res/values/strings.xml
Labels: feature ✨, 🐻주완

#33 [feat/#30] Splash UI 구현
  app/src/main/java/com/paw/key/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/login/navigation/LoginNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/java/com/paw/key/presentation/ui/main/component/MainBottomBar.kt
  app/src/main/java/com/paw/key/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/splash/navigation/SplashNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/splash/state/SplashContract.kt
  app/src/main/java/com/paw/key/presentation/ui/splash/viewmodel/SplashViewModel.kt
  app/src/main/res/drawable/ic_logo_draft.xml
  app/src/main/res/values/strings.xml
Labels: feature ✨, 🐻주완

#31 [Feat/#11] 산책하기 메인 탭 - 상위 지도 탭 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/paw/key/PawKeyApplication.kt
  app/src/main/java/com/paw/key/core/designsystem/component/LoadingScreen.kt
  app/src/main/java/com/paw/key/data/di/AppModule.kt
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/BitmapRepositoryImpl.kt
  app/src/main/java/com/paw/key/domain/repository/BitmapRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/course/CourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/EntireCourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/component/EntireCourseTabRow.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/navigation/CourseNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/state/EntireCourseContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/TapMapScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/component/tapMapView.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/navigation/TapMapNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/state/TapMapContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/viewmodel/TapMapViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/viewmodel/EntireCourseViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/WalkCourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/component/WalkRecordItem.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/component/WalkRecordRow.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/component/courseMapView.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/state/WalkCourseContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/viewmodel/WalkCourseViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/WalkCompletionScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/component/WalkCompletionHeader.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/navigation/WalkCompletionNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/viewmodel/WalkCompleteViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainTab.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/java/com/paw/key/presentation/ui/main/component/MainBottomBar.kt
  app/src/main/res/drawable/user_poi.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature ✨, 🐶민성

#34 [feat/#28] 마이페이지 산책루트 뷰 구현
  app/src/main/java/com/paw/key/core/designsystem/component/CourseCard.kt
  app/src/main/java/com/paw/key/core/designsystem/component/CourseDetail.kt
  app/src/main/java/com/paw/key/core/designsystem/component/PawkeyButton.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/PetProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/UserProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/component/TagChip.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/owner/navigation/OwnerNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/pet/navigation/PetNavigation.kt
  app/src/main/res/drawable/ic_arrow_left_black.xml
Labels: feature ✨, 😸지우

#55 [Mod/#52] SignUp 뷰 GUI 적용 및 오류 수정
  app/build.gradle.kts
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/SettingButton.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpActivityScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpDogScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/component/SignUpHeader.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/component/SignUpLoationGrid.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/component/SignUpTextField.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpActivityNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpLevelNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/state/SignUpContract.kt
Labels: 🐻주완, mod 🎉

#49 [Feat/#45] 공유용 뷰 구현
  app/src/main/java/com/paw/key/presentation/animation/FootprintAnimationScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/WalkCourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/WalkCompletionScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/navigation/WalkCompletionNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkrecord/WalkReviewScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkrecord/viewmodel/WalkReviewViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/main/state/MainContract.kt
  app/src/main/java/com/paw/key/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/region/viewmodel/RegionViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨, 🐶민성

#61 [Feat/#56] option bottomsheet 구현
  app/src/main/java/com/paw/key/presentation/ui/course/entire/EntireCourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/CourseOptionBottomSheet.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/state/TapListContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/viewmodel/TapListViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/state/TapMapContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/viewmodel/TapMapViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeLocationSettingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpActivityScreen.kt
  app/src/main/res/drawable/ic_course_list_refresh.xml
  app/src/main/res/drawable/ic_course_optin_filter.xml
  app/src/main/res/values/strings.xml
Labels: feature ✨, 🐻주완

#65 [Mod/#64] UI 수정 (홈,회원가입,필터)
  app/src/main/java/com/paw/key/core/designsystem/component/PawkeyButton.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/HomeTopBar.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/SavedCourseNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/SavedDetailNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/UserProfileNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpDogScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpScreen.kt
Labels: 🐻주완, mod 🎉

#69 [Mod/#68] 1차 QA - 홈, 온보딩, 로그인, 회원가입 디테일 수정
  app/src/main/java/com/paw/key/core/designsystem/component/PawkeyButton.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/DaytimeCard.kt
  app/src/main/java/com/paw/key/presentation/ui/home/component/RowCalendar.kt
  app/src/main/java/com/paw/key/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/onboard/OnboardingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpDogScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpLevelScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/state/SignUpContract.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable/ic_eye_linear_gray_invalid.xml
  app/src/main/res/drawable/ic_eye_linear_gray_valid.xml
  app/src/main/res/values/strings.xml
Labels: 🐻주완, mod 🎉

#73 [Feat/#63] 저장한·기록한 산책 루트 화면 ViewModel + 상태 관리 구조 적용
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/PetProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/UserProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/ArchivedDetailContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/ArchivedListContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/MyPageContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/PetProfileContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/SavedDetailContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/SavedListContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/UserProfileContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/ArchivedDetailViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/ArchivedListViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/PetProfileViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/SavedDetailViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/SavedListViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/UserProfileViewModel.kt
Labels: feature ✨, 😸지우

#77 [Feat/#70] 1차 QA , 온보딩 지역정보, 반려견 정보, 유저정보 요청 APi 연결
  app/src/main/java/com/paw/key/core/designsystem/component/CourseDetail.kt
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/request/onboarding/OnboardingInfoRequest.kt
  app/src/main/java/com/paw/key/data/dto/response/onboarding/OnboardingInfoResponse.kt
  app/src/main/java/com/paw/key/data/dto/response/onboarding/OnboardingPetsResponse.kt
  app/src/main/java/com/paw/key/data/dto/response/onboarding/OnboardingRegionResponse.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingInfoDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingPetsDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingRegionDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/OnboardingInfoRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/OnboardingRegionRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/OnboardingRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/OnboardingInfoService.kt
  app/src/main/java/com/paw/key/data/service/OnboardingPetsService.kt
  app/src/main/java/com/paw/key/data/service/OnboardingRegionService.kt
  app/src/main/java/com/paw/key/domain/model/entity/onboarding/OnboardingEntity.kt
  app/src/main/java/com/paw/key/domain/repository/OnboardingInfoRepository.kt
  app/src/main/java/com/paw/key/domain/repository/OnboardingRegionRepository.kt
  app/src/main/java/com/paw/key/domain/repository/OnboardingRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpActivityScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpLevelScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/state/SignUpContract.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/viewmodel/SignUpViewModel.kt
Labels: feature ✨, 🐻주완

#79 Feat/#78 home 지역 수정 api 연동
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/request/home/HomeRegionReqeust.kt
  app/src/main/java/com/paw/key/data/dto/response/home/HomeRegionResponse.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingInfoDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingPetsDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingRegionDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/home/HomeRegionDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/home/HomeRegionRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/onboarding/OnboardingInfoRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/onboarding/OnboardingRegionRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/onboarding/OnboardingRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/home/HomeRegionService.kt
  app/src/main/java/com/paw/key/data/service/onboarding/OnboardingInfoService.kt
  app/src/main/java/com/paw/key/data/service/onboarding/OnboardingPetsService.kt
  app/src/main/java/com/paw/key/data/service/onboarding/OnboardingRegionService.kt
  app/src/main/java/com/paw/key/domain/model/entity/home/HomeEntity.kt
  app/src/main/java/com/paw/key/domain/repository/home/HomeRegionRepository.kt
  app/src/main/java/com/paw/key/domain/repository/onboarding/OnboardingInfoRepository.kt
  app/src/main/java/com/paw/key/domain/repository/onboarding/OnboardingRegionRepository.kt
  app/src/main/java/com/paw/key/domain/repository/onboarding/OnboardingRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeLocationSettingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/navigation/HomeLocationSettingNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/home/state/HomeContract.kt
  app/src/main/java/com/paw/key/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/ArchivedDetailNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/region/RegionalManagementScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/region/navigation/RegionalNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/component/LocationList.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/viewmodel/SignUpViewModel.kt
Labels: feature ✨, 🐻주완

#83 [Feat/#82] 필터링 카테고리 옵션 조회 API 연결
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/response/filter/FilterOptionResponse.kt
  app/src/main/java/com/paw/key/data/remote/datasource/filter/FilterOptionDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/filter/FilterOptionRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/filter/FilterOptionService.kt
  app/src/main/java/com/paw/key/domain/model/entity/filter/FilterEntity.kt
  app/src/main/java/com/paw/key/domain/repository/filter/FilterOptionRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/CourseOptionBottomSheet.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/state/TapListContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/viewmodel/TapListViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walk/WalkCourseScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/walkcomplete/WalkCompletionScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/navigation/ArchivedDetailNavigation.kt
Labels: feature ✨, 🐻주완

#91 [Feat/#84] 유저 정보 등록 API 연결
  app/src/main/java/com/paw/key/core/util/PreferenceDataStore.kt
  app/src/main/java/com/paw/key/data/dto/response/onboarding/OnboardingInfoResponse.kt
  app/src/main/java/com/paw/key/data/remote/datasource/OnboardingInfoDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/onboarding/OnboardingInfoRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/onboarding/OnboardingInfoService.kt
  app/src/main/java/com/paw/key/domain/model/entity/onboarding/OnboardingEntity.kt
  app/src/main/java/com/paw/key/domain/repository/onboarding/OnboardingInfoRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeLocationSettingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/state/HomeContract.kt
  app/src/main/java/com/paw/key/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/login/navigation/LoginNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/paw/key/presentation/ui/main/PawKeyNavHost.kt
  app/src/main/java/com/paw/key/presentation/ui/region/navigation/RegionalNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpActivityScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpDogScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpLevelScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/SignUpScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpActivityNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpDogNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpLevelNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/navigation/SignUpNavigation.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/state/SignUpContract.kt
  app/src/main/java/com/paw/key/presentation/ui/signup/viewmodel/SignUpViewModel.kt
Labels: feature ✨, 🐻주완

#96 [Feat/#92] 산책 게시물 리스트 조회 API
  app/src/main/java/com/paw/key/core/designsystem/component/CourseCard.kt
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/request/list/PostsListRequestDto.kt
  app/src/main/java/com/paw/key/data/dto/response/list/PostsListResponseDto.kt
  app/src/main/java/com/paw/key/data/remote/datasource/list/PostsListDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/list/PostsListRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/list/PostsListService.kt
  app/src/main/java/com/paw/key/domain/model/entity/list/ListEntity.kt
  app/src/main/java/com/paw/key/domain/repository/list/PostsListRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/state/TapListContract.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/viewmodel/TapListViewModel.kt
Labels: feature ✨, 🐻주완

#106 [Feat/#98] 견주프로필 api
  app/src/main/java/com/paw/key/core/designsystem/component/CourseCard.kt
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/response/userprofile/UserProfileResponseDto.kt
  app/src/main/java/com/paw/key/data/remote/datasource/LikeDataSource.kt
  app/src/main/java/com/paw/key/data/remote/datasource/UserProfileDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/UserProfileRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/LikeService.kt
  app/src/main/java/com/paw/key/data/service/UserProfileService.kt
  app/src/main/java/com/paw/key/domain/model/entity/userprofile/UserProfileEntity.kt
  app/src/main/java/com/paw/key/domain/repository/LikeRepository.kt
  app/src/main/java/com/paw/key/domain/repository/userprofile/UserProfileRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/PetProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/UserProfileScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/MyPageContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/UserProfileContract.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/PetProfileViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/UserProfileViewModel.kt
Labels: feature ✨, 😸지우

#107 [Mod/#101] spalsh onboarding
  app/src/main/java/com/paw/key/presentation/ui/onboard/OnboardingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/onboard/component/OnboardPager.kt
  app/src/main/java/com/paw/key/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/ic_onboard_1.xml
  app/src/main/res/drawable/ic_onboard_2.xml
  app/src/main/res/drawable/ic_onboard_3.xml
  app/src/main/res/drawable/ic_onboard_4.xml
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/drawable/onboard1.png
  app/src/main/res/drawable/onboard2.png
  app/src/main/res/drawable/onboard3.png
  app/src/main/res/drawable/onboard4.png
Labels: feature ✨, 🐻주완

#114 Mod/#112 archived detail
  app/src/main/java/com/paw/key/core/designsystem/component/CourseDetail.kt
  app/src/main/java/com/paw/key/core/designsystem/component/TopBar.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/viewmodel/TapListViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/ArchivedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/SavedCourseDetailScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/state/ArchivedDetailContract.kt
Labels: 🐻주완, mod 🎉

#117 [Mod/#116] 현재 지역 조회 API 연결
  app/src/main/java/com/paw/key/core/util/PreferenceDataStore.kt
  app/src/main/java/com/paw/key/data/di/RepositoryModule.kt
  app/src/main/java/com/paw/key/data/di/ServiceModule.kt
  app/src/main/java/com/paw/key/data/dto/response/home/RegionCurrentResponseDto.kt
  app/src/main/java/com/paw/key/data/remote/datasource/home/RegionCurrentDataSource.kt
  app/src/main/java/com/paw/key/data/repositoryimpl/home/RegionCurrentRepositoryImpl.kt
  app/src/main/java/com/paw/key/data/service/home/RegionCurrentService.kt
  app/src/main/java/com/paw/key/domain/model/entity/home/HomeEntity.kt
  app/src/main/java/com/paw/key/domain/repository/home/RegionCurrentRepository.kt
  app/src/main/java/com/paw/key/presentation/ui/course/entire/tab/map/List/TabListScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeLocationSettingScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/paw/key/presentation/ui/home/state/HomeContract.kt
  app/src/main/java/com/paw/key/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/paw/key/presentation/ui/mypage/viewmodel/UserProfileViewModel.kt
Labels: 🐻주완, mod 🎉

#129 [Docs/#128] readme update
  README.md
Labels: 🐻주완, docs 📝
